### PR TITLE
Embed ui assets

### PR DESCRIPTION
**Pull request by skwerlman**

### CODE REVIEW

**Comment by Gama11** [comment]
I would like @larsiusprime's opinion on this one... There seems to be a certain size limit for embedded assets, which some people might hit because of this? Not sure how big all flixel-ui assets put together are.

**Comment by bendmorris** [comment]
How about a conditional?

    <assets path="assets/images" rename="flixel/flixel-ui/img" unless="FLXUI_EMBED_ASSETS"/>
    <assets path="assets/images" rename="flixel/flixel-ui/img" embed="true" if="FLXUI_EMBED_ASSETS"/>

**Comment by Gama11** [comment]
That's a reasonable solution if it's indeed an issue. If not, I'd prefer to avoid introducing conditionals.

**Comment by skwerlman** [comment]
I personally can't think of any cases where I'd want to avoid embedding the default assets, but I'm happy to add a conditional if you guys think its worth it.

**Comment by Gama11** [comment]
I just checked, flixel-ui's assets appear to only have 33.2 KB in total - I doubt that'll cause any issues. Let's just merge it as is for now.

Thanks!

**Pull request merged**
