### PR TITLE
Return scaled center coordinates for widgets

### PR DESCRIPTION
**Pull request by DigiEggz**
The button width / height always return the center values of the native button. At larger scale modes, the disparity grows enough that other buttons can sometimes be pressed when overlapping each other because it doesn't return the actual center coordinates.

### CODE REVIEW

**Comment by Geokureli** [comment]
Can I get a simple test case that quickly highlights the benefit of this change?

**Comment by DigiEggz** [comment]
The widget function `_getWidgetPoint()`, which is used when clicking buttons, does not return the correct center point when the screen is scaled. When the scale factor changes, the buttons width and height need to use the camera's `totalScaleX` and `totalScaleY` values, respectively. This causes misclicks at higher resolutions, especially when buttons are close together.

Red X marks render where the button reports the button center at a scale of 3x. The green X marks render at a scaled resolution of 10x. The marks should always overlap, no matter the scale mode.

For clarity, here is what the buttons bounding boxes look like:

bb


Reported centers **before** the change:

b1
(2560 × 1440, totalScale: 3)

b2
(2560 × 1440, totalScale: 10)




Reported centers **after** the change:

a1
(2560 × 1440, totalScale: 3)

a2
(2560 × 1440, totalScale: 10)

In the "before the change" section, you can see the button centers report different values (from the misaligned X marks) when the game is at a different scale factors. The locations are also very high up on the button and not actually centered, either.

**Comment by DigiEggz** [comment]
To summarize, create a list of widgets for a FlxUICursor to traverse. Then enter fullscreen at different screen resolutions. The cursor always reports the original coordinates instead of the new scaled coordinates.

**Comment by Geokureli** [comment]
sorry for the holdup, been really busy, can you merge the dev branch into this to fix CI, I'll try to get to this soon

**Comment by Geokureli** [comment]
I'm finally looking into this, and I don't quite understand the issue, you mark invalid centers on your images, but when I run the [Cursor Demo](https://haxeflixel.com/demos/Cursor/) with a scale of 4 I get no issues with clicking or the cursor's position.

How are you achieving a totalScale of 3, or 10. And what actual code is failing that depends on these centers?

**Comment by DigiEggz** [comment]
FlxUICursor uses `Camera.totalScaleX` and `Camera.totalScaleY` to determine coordinates for the widget point. When the game is scaled, the totalScale values increase.  I got the scale value to increase by entering fullscreen, which happens to increase the scale to 10. The author forgot to adjust the center widget coordinates by this scale factor, despite correctly doing so a few lines above. 

You will not experience any issues at smaller resolutions because the disparity is not large enough to cause errant clicks, depending on your button size. As the scale size increases, the difference of the "center" becomes to large that it starts to overlap other buttons. You can see that the center is wrong by tracing out the center coordinate of any widget. The value should change with the scale size.

The X's were placed programmatically. You can see that the "center" location is too high in the first section and it only gets worse as the scale size grows.

**Comment by Geokureli** [comment]
@DigiEggz I'm still not seeing it even with very large scales, does this happen to you with the Cursor demo? I need a solid way to reproduce this issue

**Comment by DigiEggz** [comment]
I'll work on something to show you soon. Happy holidays!

**Comment by DigiEggz** [comment]
I've attached a sample project. Please excuse the absurd verbosity—I tried to make this as fast as I could because I have an event and need to head out.

[Demo.zip](https://github.com/HaxeFlixel/flixel-ui/files/13757433/Demo.zip)

Use the arrow keys to traverse the list and then press the **X** key or Enter to select a button. Press the **S** key to view the current scale.

At lower scale factors, the button presses normally. Next, either drag the window or go fullscreen with **F**. At any scale factor of roughly 6.5 or greater, multiple buttons are pressed when you press X or Enter. It also traces out multiple keypresses at once.

**Comment by Geokureli** [comment]
I tried the demo, I cannot see a difference in behavior with or without this change. fullscreen seems to have no effect on my behavior, either. No matter what, FlxUICursor presses multiple buttons when I press X, with this change, without it, fullscreen or not. I also see no change in the behavior of mouseover

I'm on mac, my fullscreen scale is 12, I don't know if you're on windows or linux or something but I can try those. Also there's no urgency on this, feel free to come back to this after the holidays, I know this time can be hectic for some

**Comment by DigiEggz** [comment]
That's very strange. I've also been testing on macOS, so the difference may lie elsewhere. I'll try and make a video when I get the chance. If you spawn a graphic where the widget center point is, does the center point stay in the same location each time you create one at different scales? I noticed that the center point was always reporting the native size values of the widget.

**Comment by Geokureli** [comment]
Sorry for the hold-up just needed to make sure I could reproduce the actual symptoms

**Pull request merged**
