### PR TITLE
Also fix comments

### PR DESCRIPTION
**Pull request by buckle2000**

### CODE REVIEW

**Comment by Gama11** [comment]
Looks like this was already included in the previous merge: https://github.com/HaxeFlixel/flixel-ui/commit/d544aecd61a9e25657de868739224d91a617a5d0

**Comment by buckle2000** [comment]
I don't understand.

**Comment by Gama11** [comment]
Well, you pushed the changes to the same branch? That will update the PR. Or what do you mean?

**Comment by buckle2000** [comment]
I know that, but if I create a new pull request:
default

**Comment by Gama11** [comment]
Hm, yeah, I see the same: https://github.com/HaxeFlixel/flixel-ui/compare/dev...buckle2000:dev?expand=1

That is pretty weird..

**Comment by Gama11** [comment]
If I diff the branches locally in SourceTree, there are no differences. This must be a GitHub bug, never seen anything like it...

**Comment by buckle2000** [comment]
I pulled from Haxeflixel's flixel-ui to mine and fixed this problem. Not sure why.

**Pull request closed without merging**
