### PR TITLE
The Mouse shouldn't be visible acually.

### PR DESCRIPTION
**Pull request by MAJigsaw77**
Title

### CODE REVIEW

**Comment by Geokureli** [comment]
Not sure about this, it can easily be disabled in projects that don't want it, but disabling it for all projects could break existing projects in a way thats easy to miss. Also, I feel like if you don't want the mouse you shouldn't be using `FlxUISubState`

**Comment by MAJigsaw77** [comment]
But in `FlxUIState` isn't visible.

**Comment by MAJigsaw77** [comment]
It's kinda nonsense to have it not visible in the state but in the SubState to be visible.

**Comment by Geokureli** [comment]
try `myFlxUIState.hideCursorOnSubstate = false`
https://github.com/HaxeFlixel/flixel-ui/blob/dev/flixel/addons/ui/FlxUIState.hx#L277

**Comment by MAJigsaw77** [comment]
Ok, the pr is nonsense now

**Comment by MAJigsaw77** [comment]
Thanks for showing this to me

**Comment by Geokureli** [comment]
just wanna doublecheck and make sure that worked, I've never used this

**Pull request closed without merging**
